#!/bin/bash

# Ensure the script is run as root
if [ "$EUID" -ne 0 ]; then
    echo "[ERROR] This script must be run as root (sudo)."
    exit 1
fi

CONF_FILE="/etc/modprobe.d/90-remove-legacy-modules.conf"

echo "[INFO] Starting legacy kernel module disabling process..."

# Create or overwrite the configuration file
echo "# Auto-generated by legacy module removal script" > "$CONF_FILE"

# 1. Disable Old Storage & Filesystems (FAT12/16, Floppy, etc.)
echo "[INFO] Disabling legacy filesystems and storage modules..."
{
    echo "# Legacy Filesystems & Storage"
    echo "blacklist msdos"
    echo "install msdos /bin/true"
    echo "blacklist vfat"
    echo "install vfat /bin/true"
    echo "blacklist floppy"
    echo "install floppy /bin/true"
} >> "$CONF_FILE"

# Note: Disabling 'vfat' will disable FAT12, FAT16, and FAT32. 
# WARNING: If your system uses EFI stub booting directly without a standard GRUB setup 
# that pre-loads VFAT, ensuring this doesn't conflict with /boot/efi is recommended.

# 2. Disable 1990s Networking Protocols (Amateur Radio, Token Ring, AppleTalk)
echo "[INFO] Disabling obsolete 90s networking protocols..."
{
    echo -e "\n# Obsolete 1990s Protocols"
    echo "blacklist ax25"
    echo "install ax25 /bin/true"
    echo "blacklist netrom"
    echo "install netrom /bin/true"
    echo "blacklist rose"
    echo "install rose /bin/true"
    echo "blacklist appletalk"
    echo "install appletalk /bin/true"
    echo "blacklist ipx"
    echo "install ipx /bin/true"
    echo "blacklist p8023"
    echo "install p8023 /bin/true"
    echo "blacklist psnap"
    echo "install psnap /bin/true"
    echo "blacklist llc"
    echo "install llc /bin/true"
} >> "$CONF_FILE"

# 3. Disable Other Ancient/Rare Filesystems
echo "[INFO] Disabling ancient filesystem modules..."
{
    echo -e "\n# Unused Ancient Filesystems"
    echo "blacklist hfs"
    echo "install hfs /bin/true"
    echo "blacklist hfsplus"
    echo "install hfsplus /bin/true"
    echo "blacklist squashfs"
    echo "install squashfs /bin/true"
    echo "blacklist udf"
    echo "install udf /bin/true"
} >> "$CONF_FILE"

echo "[SUCCESS] Configuration file created at $CONF_FILE"
echo "[INFO] Unloading currently active modules from memory (if loaded)..."

# Try to unload modules immediately if they are not active
modules=("msdos" "floppy" "ax25" "netrom" "rose" "appletalk" "ipx" "hfs" "hfsplus")
for mod in "${modules[@]}"; do
    rmmod "$mod" 2>/dev/null && echo "[REMOVED] Unloaded active module: $mod"
done

echo "[SUCCESS] Process completed. Please reboot your system to apply all changes cleanly."
